# Generated by Django 4.1.5 on 2023-01-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktail_book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vodka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
