# Generated by Django 4.1.5 on 2023-01-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktail_book", "0003_rum"),
    ]

    operations = [
        migrations.AddField(
            model_name="vodka",
            name="description",
            field=models.TextField(default="", max_length="1000"),
        ),
    ]
