# Generated by Django 4.1.5 on 2023-02-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktail_book", "0005_gin_tequila_whiskey_delete_cocktail_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="gin", name="price",),
        migrations.RemoveField(model_name="rum", name="price",),
        migrations.RemoveField(model_name="tequila", name="price",),
        migrations.RemoveField(model_name="vodka", name="price",),
        migrations.RemoveField(model_name="whiskey", name="price",),
        migrations.AddField(
            model_name="gin",
            name="notes",
            field=models.TextField(default="", max_length="1000"),
        ),
        migrations.AddField(
            model_name="rum",
            name="notes",
            field=models.TextField(default="", max_length="1000"),
        ),
        migrations.AddField(
            model_name="tequila",
            name="notes",
            field=models.TextField(default="", max_length="1000"),
        ),
        migrations.AddField(
            model_name="vodka",
            name="notes",
            field=models.TextField(default="", max_length="1000"),
        ),
        migrations.AddField(
            model_name="whiskey",
            name="notes",
            field=models.TextField(default="", max_length="1000"),
        ),
    ]
