# Generated by Django 4.1.5 on 2023-02-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktail_book", "0007_vodka_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="gin",
            name="image",
            field=models.ImageField(default="", upload_to="img/"),
        ),
        migrations.AddField(
            model_name="rum",
            name="image",
            field=models.ImageField(default="", upload_to="img/"),
        ),
        migrations.AddField(
            model_name="tequila",
            name="image",
            field=models.ImageField(default="", upload_to="img/"),
        ),
        migrations.AddField(
            model_name="whiskey",
            name="image",
            field=models.ImageField(default="", upload_to="img/"),
        ),
    ]
