# Generated by Django 4.1.5 on 2023-02-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktail_book", "0008_gin_image_rum_image_tequila_image_whiskey_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vodka", name="ingredients", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="vodka", name="instructions", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="vodka", name="notes", field=models.TextField(),
        ),
    ]
