# Generated by Django 4.1.5 on 2023-02-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cocktail_book",
            "0009_alter_vodka_ingredients_alter_vodka_instructions_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="gin",
            name="image",
            field=models.ImageField(default="", upload_to="static/img/"),
        ),
    ]
