# Generated by Django 4.1.5 on 2023-02-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktail_book", "0010_alter_gin_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gin",
            name="image",
            field=models.ImageField(default="", upload_to="img/"),
        ),
    ]
