# Generated by Django 4.1.5 on 2023-02-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktail_book", "0011_alter_gin_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="gin",
            name="background",
            field=models.TextField(default="", max_length="2000"),
        ),
        migrations.AddField(
            model_name="rum",
            name="background",
            field=models.TextField(default="", max_length="2000"),
        ),
        migrations.AddField(
            model_name="tequila",
            name="background",
            field=models.TextField(default="", max_length="2000"),
        ),
        migrations.AddField(
            model_name="vodka",
            name="background",
            field=models.TextField(default="", max_length="2000"),
        ),
        migrations.AddField(
            model_name="whiskey",
            name="background",
            field=models.TextField(default="", max_length="2000"),
        ),
    ]
