# Generated by Django 4.1.7 on 2023-02-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cocktail_book",
            "0012_gin_background_rum_background_tequila_background_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vodka",
            name="image",
            field=models.ImageField(default="", upload_to="media/img/"),
        ),
    ]
