# Generated by Django 4.1.7 on 2023-02-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktail_book", "0013_alter_vodka_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gin",
            name="image",
            field=models.ImageField(default="", upload_to="media/img/"),
        ),
        migrations.AlterField(
            model_name="rum",
            name="image",
            field=models.ImageField(default="", upload_to="media/img/"),
        ),
        migrations.AlterField(
            model_name="tequila",
            name="image",
            field=models.ImageField(default="", upload_to="media/img/"),
        ),
        migrations.AlterField(
            model_name="whiskey",
            name="image",
            field=models.ImageField(default="", upload_to="media/img/"),
        ),
    ]
