# Generated by Django 4.1.5 on 2023-01-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="cocktail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("ingredients", models.TextField(max_length=500)),
                ("instructions", models.TextField(max_length=500)),
            ],
        ),
    ]
